package DTOs;

public enum ResultCode {
    ERROR_REGISTER,
    ERROR_SETUP,
    ERROR_LOGIN,
    ERROR_CART_MODIFICATION,
    ERROR_PURCHASE,
    ERROR_STORE_PRODUCT_MODIFICATION,
    ERROR_STORE_OWNER_MODIFICATION,
    ERROR_STORE_BUYING_POLICY_CHANGE,
    ERROR_STORE_DISCOUNT_POLICY_CHANGE,
    ERROR_STORE_MANAGER_MODIFICATION,
    ERROR_LOGOUT,
    ERROR_SESSIONID,
    ERROR_OPENSTORE,
    ERROR_SUBID, ERROR_HISTORY, ERROR_STOREHISTORY, ERROR_ADMIN, ERROR_STOREID, ERROR_GETUSERS, ERROR_GUESTUSERS, ERROR_CHANGE_PRODUCT_PRICE, ERROR_DELETE, ERROR_DATABASE, ERROR_PAYMENT_DENIED, ERROR_PAYMENT_SYSTEM_UNAVAILABLE, ERROR_SUPPLY_DENIED, ERROR_SUPPLY_SYSTEM_UNAVAILABLE, SUCCESS

}
