package DTOs;

public enum ResultCode {
    ERROR_LOGIN, ERROR_CART_MODIFICATION, ERROR_PURCHASE, ERROR_STORE_PRODUCT_MODIFICATION, ERROR_STORE_OWNER_MODIFICATION, ERROR_STORE_BUYING_POLICY_CHANGE, ERROR_STORE_MANAGER_MODIFICATION, ERROR_LOGOUT, SUCCESS

}
